## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [4]:
# 設定 data_path
dir_data = '../data/'

In [5]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ../data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [6]:
app_train.shape

(307511, 122)

#### 列出所有欄位

In [7]:
app_train.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

#### 截取部分資料

In [8]:
app_train.iloc[:100,3:6]

   CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY
0            M            N               Y
1            F            N               N
2            M            Y               Y
3            F            N               Y
4            M            N               Y
5            M            N               Y
6            F            Y               Y
7            M            Y               Y
8            F            N               Y
9            M            N               Y
10           F            N               Y
11           F            N               Y
12           F            N               Y
13           M            Y               N
14           F            N               Y
15           M            Y               Y
16           M            N               N
17           F            N               Y
18           F            N               Y
19           F            N               Y
20           M            Y               Y
21           F            Y               Y
22           F            N               N
23           F            N               Y
24           M            Y               N
25           F            N               Y
26           F            N               Y
27           M            N               Y
28           M            Y               Y
29           M            N               Y
..         ...          ...             ...
70           M            N               N
71           M            Y               Y
72           M            N               Y
73           M            N               Y
74           F            N               Y
75           F            N               Y
76           F            N               N
77           M            N               Y
78           F            N               Y
79           F            N               Y
80           F            N               Y
81           F            N               Y
82           M            Y               Y
83           M            Y               N
84           F            N               Y
85           M            Y               Y
86           F            Y               Y
87           F            N               N
88           F            N               Y
89           F            N               Y
90           F            N               Y
91           F            N               Y
92           M            Y               Y
93           F            Y               N
94           M            Y               Y
95           M            Y               N
96           F            N               Y
97           F            N               N
98           F            N               Y
99           F            N               Y

[100 rows x 3 columns]

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子